service: mellow-scheduler

provider:
  name: aws
  runtime: nodejs12.x

functions:
  startScheduledCook:
    handler: handler.startScheduledCook
    events:
      - http:
          path: schedule
          method: post
          integraiton: lambda-proxy
          cors: true
